//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../Volta.g4//VoltaParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVoltaParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class VoltaParserBaseListener : IVoltaParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] VoltaParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] VoltaParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.constDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstDecl([NotNull] VoltaParser.ConstDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.constDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstDecl([NotNull] VoltaParser.ConstDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] VoltaParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] VoltaParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDecl([NotNull] VoltaParser.ClassDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDecl([NotNull] VoltaParser.ClassDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.methodDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDecl([NotNull] VoltaParser.MethodDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.methodDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDecl([NotNull] VoltaParser.MethodDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.formPars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormPars([NotNull] VoltaParser.FormParsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.formPars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormPars([NotNull] VoltaParser.FormParsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] VoltaParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] VoltaParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] VoltaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] VoltaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] VoltaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] VoltaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.actPars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActPars([NotNull] VoltaParser.ActParsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.actPars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActPars([NotNull] VoltaParser.ActParsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] VoltaParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] VoltaParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.condTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondTerm([NotNull] VoltaParser.CondTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.condTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondTerm([NotNull] VoltaParser.CondTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.condFact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondFact([NotNull] VoltaParser.CondFactContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.condFact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondFact([NotNull] VoltaParser.CondFactContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] VoltaParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] VoltaParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] VoltaParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] VoltaParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] VoltaParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] VoltaParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignator([NotNull] VoltaParser.DesignatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignator([NotNull] VoltaParser.DesignatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.mulop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulop([NotNull] VoltaParser.MulopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.mulop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulop([NotNull] VoltaParser.MulopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.addop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddop([NotNull] VoltaParser.AddopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.addop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddop([NotNull] VoltaParser.AddopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelop([NotNull] VoltaParser.RelopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelop([NotNull] VoltaParser.RelopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.switch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch([NotNull] VoltaParser.SwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.switch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch([NotNull] VoltaParser.SwitchContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
