//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../Volta.g4//VoltaParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VoltaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IVoltaParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] VoltaParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] VoltaParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDecl([NotNull] VoltaParser.ConstDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDecl([NotNull] VoltaParser.ConstDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] VoltaParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] VoltaParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDecl([NotNull] VoltaParser.ClassDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDecl([NotNull] VoltaParser.ClassDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDecl([NotNull] VoltaParser.MethodDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDecl([NotNull] VoltaParser.MethodDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.formPars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormPars([NotNull] VoltaParser.FormParsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.formPars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormPars([NotNull] VoltaParser.FormParsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] VoltaParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] VoltaParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] VoltaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] VoltaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] VoltaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] VoltaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.actPars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActPars([NotNull] VoltaParser.ActParsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.actPars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActPars([NotNull] VoltaParser.ActParsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] VoltaParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] VoltaParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.condTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondTerm([NotNull] VoltaParser.CondTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.condTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondTerm([NotNull] VoltaParser.CondTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.condFact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondFact([NotNull] VoltaParser.CondFactContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.condFact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondFact([NotNull] VoltaParser.CondFactContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] VoltaParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] VoltaParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] VoltaParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] VoltaParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] VoltaParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] VoltaParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignator([NotNull] VoltaParser.DesignatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignator([NotNull] VoltaParser.DesignatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.mulop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulop([NotNull] VoltaParser.MulopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.mulop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulop([NotNull] VoltaParser.MulopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.addop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddop([NotNull] VoltaParser.AddopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.addop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddop([NotNull] VoltaParser.AddopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelop([NotNull] VoltaParser.RelopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelop([NotNull] VoltaParser.RelopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoltaParser.switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch([NotNull] VoltaParser.SwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoltaParser.switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch([NotNull] VoltaParser.SwitchContext context);
}
