//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../Volta.g4//VoltaParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class VoltaParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		NOT=1, HASH=2, DOLAR=3, AND=4, OR=5, BL=6, BR=7, SEMICOLON=8, ADD=9, ADDADD=10, 
		SUB=11, SUBSUB=12, MUL=13, DIV=14, MDIV=15, EQUALEQUAL=16, NOTEQUAL=17, 
		GREATEREQUAL=18, LESSEQUAL=19, EQUAL=20, GREATER=21, LESS=22, CURLYBL=23, 
		CURLYBR=24, SQUAREBL=25, SQUAREBR=26, COLON=27, DOT=28, COMMA=29, QUESTIONMARK=30, 
		CLASS=31, CONST=32, ELSE=33, IF=34, NEW=35, READ=36, RETURN=37, VOID=38, 
		WHILE=39, WRITE=40, TRUE=41, FALSE=42, FOR=43, SWITCH=44, CASE=45, BREAK=46, 
		DEFAULT=47, IDENT=48, NUM=49, CHARCONST=50, STRING=51, COMMENT=52, WS=53;
	public const int
		RULE_program = 0, RULE_constDecl = 1, RULE_varDecl = 2, RULE_classDecl = 3, 
		RULE_methodDecl = 4, RULE_formPars = 5, RULE_type = 6, RULE_statement = 7, 
		RULE_block = 8, RULE_actPars = 9, RULE_condition = 10, RULE_condTerm = 11, 
		RULE_condFact = 12, RULE_expr = 13, RULE_term = 14, RULE_factor = 15, 
		RULE_designator = 16, RULE_mulop = 17, RULE_addop = 18, RULE_relop = 19, 
		RULE_switch = 20;
	public static readonly string[] ruleNames = {
		"program", "constDecl", "varDecl", "classDecl", "methodDecl", "formPars", 
		"type", "statement", "block", "actPars", "condition", "condTerm", "condFact", 
		"expr", "term", "factor", "designator", "mulop", "addop", "relop", "switch"
	};

	private static readonly string[] _LiteralNames = {
		null, "'!'", "'#'", "'$'", "'&&'", "'||'", "'('", "')'", "';'", "'+'", 
		"'++'", "'-'", "'--'", "'*'", "'/'", "'%'", "'=='", "'!='", "'>='", "'<='", 
		"'='", "'>'", "'<'", "'{'", "'}'", "'['", "']'", "':'", "'.'", "','", 
		"'?'", "'class'", "'const'", "'else'", "'if'", "'new'", "'read'", "'return'", 
		"'void'", "'while'", "'write'", "'true'", "'false'", "'for'", "'switch'", 
		"'case'", "'break'", "'default'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "NOT", "HASH", "DOLAR", "AND", "OR", "BL", "BR", "SEMICOLON", "ADD", 
		"ADDADD", "SUB", "SUBSUB", "MUL", "DIV", "MDIV", "EQUALEQUAL", "NOTEQUAL", 
		"GREATEREQUAL", "LESSEQUAL", "EQUAL", "GREATER", "LESS", "CURLYBL", "CURLYBR", 
		"SQUAREBL", "SQUAREBR", "COLON", "DOT", "COMMA", "QUESTIONMARK", "CLASS", 
		"CONST", "ELSE", "IF", "NEW", "READ", "RETURN", "VOID", "WHILE", "WRITE", 
		"TRUE", "FALSE", "FOR", "SWITCH", "CASE", "BREAK", "DEFAULT", "IDENT", 
		"NUM", "CHARCONST", "STRING", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "VoltaParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static VoltaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public VoltaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public VoltaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		public ITerminalNode CLASS() { return GetToken(VoltaParser.CLASS, 0); }
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ITerminalNode CURLYBL() { return GetToken(VoltaParser.CURLYBL, 0); }
		public ITerminalNode CURLYBR() { return GetToken(VoltaParser.CURLYBR, 0); }
		public ITerminalNode Eof() { return GetToken(VoltaParser.Eof, 0); }
		public ConstDeclContext[] constDecl() {
			return GetRuleContexts<ConstDeclContext>();
		}
		public ConstDeclContext constDecl(int i) {
			return GetRuleContext<ConstDeclContext>(i);
		}
		public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		public ClassDeclContext[] classDecl() {
			return GetRuleContexts<ClassDeclContext>();
		}
		public ClassDeclContext classDecl(int i) {
			return GetRuleContext<ClassDeclContext>(i);
		}
		public MethodDeclContext[] methodDecl() {
			return GetRuleContexts<MethodDeclContext>();
		}
		public MethodDeclContext methodDecl(int i) {
			return GetRuleContext<MethodDeclContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42; Match(CLASS);
			State = 43; Match(IDENT);
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << CLASS) | (1L << CONST) | (1L << IDENT))) != 0)) {
				{
				State = 47;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case CONST:
					{
					State = 44; constDecl();
					}
					break;
				case IDENT:
					{
					State = 45; varDecl();
					}
					break;
				case CLASS:
					{
					State = 46; classDecl();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 52; Match(CURLYBL);
			State = 56;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==VOID || _la==IDENT) {
				{
				{
				State = 53; methodDecl();
				}
				}
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 59; Match(CURLYBR);
			State = 60; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstDeclContext : ParserRuleContext {
		public ITerminalNode CONST() { return GetToken(VoltaParser.CONST, 0); }
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ITerminalNode EQUAL() { return GetToken(VoltaParser.EQUAL, 0); }
		public ITerminalNode SEMICOLON() { return GetToken(VoltaParser.SEMICOLON, 0); }
		public ITerminalNode NUM() { return GetToken(VoltaParser.NUM, 0); }
		public ITerminalNode CHARCONST() { return GetToken(VoltaParser.CHARCONST, 0); }
		public ITerminalNode STRING() { return GetToken(VoltaParser.STRING, 0); }
		public ConstDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterConstDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitConstDecl(this);
		}
	}

	[RuleVersion(0)]
	public ConstDeclContext constDecl() {
		ConstDeclContext _localctx = new ConstDeclContext(Context, State);
		EnterRule(_localctx, 2, RULE_constDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62; Match(CONST);
			State = 63; type();
			State = 64; Match(IDENT);
			State = 65; Match(EQUAL);
			State = 66;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NUM) | (1L << CHARCONST) | (1L << STRING))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 67; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclContext : ParserRuleContext {
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode[] IDENT() { return GetTokens(VoltaParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(VoltaParser.IDENT, i);
		}
		public ITerminalNode SEMICOLON() { return GetToken(VoltaParser.SEMICOLON, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(VoltaParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(VoltaParser.COMMA, i);
		}
		public VarDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterVarDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitVarDecl(this);
		}
	}

	[RuleVersion(0)]
	public VarDeclContext varDecl() {
		VarDeclContext _localctx = new VarDeclContext(Context, State);
		EnterRule(_localctx, 4, RULE_varDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; type();
			State = 70; Match(IDENT);
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 71; Match(COMMA);
				State = 72; Match(IDENT);
				}
				}
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 78; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassDeclContext : ParserRuleContext {
		public ITerminalNode CLASS() { return GetToken(VoltaParser.CLASS, 0); }
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ITerminalNode CURLYBL() { return GetToken(VoltaParser.CURLYBL, 0); }
		public VarDeclContext varDecl() {
			return GetRuleContext<VarDeclContext>(0);
		}
		public ITerminalNode CURLYBR() { return GetToken(VoltaParser.CURLYBR, 0); }
		public ClassDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterClassDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitClassDecl(this);
		}
	}

	[RuleVersion(0)]
	public ClassDeclContext classDecl() {
		ClassDeclContext _localctx = new ClassDeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_classDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80; Match(CLASS);
			State = 81; Match(IDENT);
			State = 82; Match(CURLYBL);
			State = 83; varDecl();
			State = 84; Match(CURLYBR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodDeclContext : ParserRuleContext {
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ITerminalNode BL() { return GetToken(VoltaParser.BL, 0); }
		public ITerminalNode BR() { return GetToken(VoltaParser.BR, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode VOID() { return GetToken(VoltaParser.VOID, 0); }
		public FormParsContext formPars() {
			return GetRuleContext<FormParsContext>(0);
		}
		public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		public MethodDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterMethodDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitMethodDecl(this);
		}
	}

	[RuleVersion(0)]
	public MethodDeclContext methodDecl() {
		MethodDeclContext _localctx = new MethodDeclContext(Context, State);
		EnterRule(_localctx, 8, RULE_methodDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENT:
				{
				State = 86; type();
				}
				break;
			case VOID:
				{
				State = 87; Match(VOID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 90; Match(IDENT);
			State = 91; Match(BL);
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENT) {
				{
				State = 92; formPars();
				}
			}

			State = 95; Match(BR);
			State = 99;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENT) {
				{
				{
				State = 96; varDecl();
				}
				}
				State = 101;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 102; block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormParsContext : ParserRuleContext {
		public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		public ITerminalNode[] IDENT() { return GetTokens(VoltaParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(VoltaParser.IDENT, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(VoltaParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(VoltaParser.COMMA, i);
		}
		public FormParsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formPars; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterFormPars(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitFormPars(this);
		}
	}

	[RuleVersion(0)]
	public FormParsContext formPars() {
		FormParsContext _localctx = new FormParsContext(Context, State);
		EnterRule(_localctx, 10, RULE_formPars);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; type();
			State = 105; Match(IDENT);
			State = 112;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				{
				State = 106; Match(COMMA);
				}
				State = 107; type();
				State = 108; Match(IDENT);
				}
				}
				State = 114;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ITerminalNode SQUAREBL() { return GetToken(VoltaParser.SQUAREBL, 0); }
		public ITerminalNode SQUAREBR() { return GetToken(VoltaParser.SQUAREBR, 0); }
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 12, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115; Match(IDENT);
			State = 118;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SQUAREBL) {
				{
				State = 116; Match(SQUAREBL);
				State = 117; Match(SQUAREBR);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public DesignatorContext designator() {
			return GetRuleContext<DesignatorContext>(0);
		}
		public ITerminalNode[] SEMICOLON() { return GetTokens(VoltaParser.SEMICOLON); }
		public ITerminalNode SEMICOLON(int i) {
			return GetToken(VoltaParser.SEMICOLON, i);
		}
		public ITerminalNode EQUAL() { return GetToken(VoltaParser.EQUAL, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode BL() { return GetToken(VoltaParser.BL, 0); }
		public ITerminalNode BR() { return GetToken(VoltaParser.BR, 0); }
		public ITerminalNode ADDADD() { return GetToken(VoltaParser.ADDADD, 0); }
		public ITerminalNode SUBSUB() { return GetToken(VoltaParser.SUBSUB, 0); }
		public ActParsContext actPars() {
			return GetRuleContext<ActParsContext>(0);
		}
		public ITerminalNode IF() { return GetToken(VoltaParser.IF, 0); }
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode ELSE() { return GetToken(VoltaParser.ELSE, 0); }
		public ITerminalNode FOR() { return GetToken(VoltaParser.FOR, 0); }
		public ITerminalNode WHILE() { return GetToken(VoltaParser.WHILE, 0); }
		public ITerminalNode BREAK() { return GetToken(VoltaParser.BREAK, 0); }
		public SwitchContext @switch() {
			return GetRuleContext<SwitchContext>(0);
		}
		public ITerminalNode RETURN() { return GetToken(VoltaParser.RETURN, 0); }
		public ITerminalNode READ() { return GetToken(VoltaParser.READ, 0); }
		public ITerminalNode WRITE() { return GetToken(VoltaParser.WRITE, 0); }
		public ITerminalNode COMMA() { return GetToken(VoltaParser.COMMA, 0); }
		public ITerminalNode NUM() { return GetToken(VoltaParser.NUM, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_statement);
		int _la;
		try {
			State = 188;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 120; designator();
				State = 130;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case EQUAL:
					{
					State = 121; Match(EQUAL);
					State = 122; expr();
					}
					break;
				case BL:
					{
					State = 123; Match(BL);
					State = 125;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BL) | (1L << SUB) | (1L << NEW) | (1L << TRUE) | (1L << FALSE) | (1L << IDENT) | (1L << NUM) | (1L << CHARCONST))) != 0)) {
						{
						State = 124; actPars();
						}
					}

					State = 127; Match(BR);
					}
					break;
				case ADDADD:
					{
					State = 128; Match(ADDADD);
					}
					break;
				case SUBSUB:
					{
					State = 129; Match(SUBSUB);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 132; Match(SEMICOLON);
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 2);
				{
				State = 134; Match(IF);
				State = 135; Match(BL);
				State = 136; condition();
				State = 137; Match(BR);
				State = 138; statement();
				State = 141;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
				case 1:
					{
					State = 139; Match(ELSE);
					State = 140; statement();
					}
					break;
				}
				}
				break;
			case FOR:
				EnterOuterAlt(_localctx, 3);
				{
				State = 143; Match(FOR);
				State = 144; Match(BL);
				State = 145; expr();
				State = 146; Match(SEMICOLON);
				State = 148;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BL) | (1L << SUB) | (1L << NEW) | (1L << TRUE) | (1L << FALSE) | (1L << IDENT) | (1L << NUM) | (1L << CHARCONST))) != 0)) {
					{
					State = 147; condition();
					}
				}

				State = 150; Match(SEMICOLON);
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << SEMICOLON) | (1L << CURLYBL) | (1L << IF) | (1L << READ) | (1L << RETURN) | (1L << WHILE) | (1L << WRITE) | (1L << FOR) | (1L << SWITCH) | (1L << BREAK) | (1L << IDENT))) != 0)) {
					{
					State = 151; statement();
					}
				}

				State = 154; Match(BR);
				State = 155; statement();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 157; Match(WHILE);
				State = 158; Match(BL);
				State = 159; condition();
				State = 160; Match(BR);
				State = 161; statement();
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 5);
				{
				State = 163; Match(BREAK);
				State = 164; Match(SEMICOLON);
				}
				break;
			case SWITCH:
				EnterOuterAlt(_localctx, 6);
				{
				State = 165; @switch();
				}
				break;
			case RETURN:
				EnterOuterAlt(_localctx, 7);
				{
				State = 166; Match(RETURN);
				State = 168;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
				case 1:
					{
					State = 167; expr();
					}
					break;
				}
				}
				break;
			case READ:
				EnterOuterAlt(_localctx, 8);
				{
				State = 170; Match(READ);
				State = 171; Match(BL);
				State = 172; designator();
				State = 173; Match(BR);
				State = 174; Match(SEMICOLON);
				}
				break;
			case WRITE:
				EnterOuterAlt(_localctx, 9);
				{
				State = 176; Match(WRITE);
				State = 177; Match(BL);
				State = 178; expr();
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMA) {
					{
					State = 179; Match(COMMA);
					State = 180; Match(NUM);
					}
				}

				State = 183; Match(BR);
				State = 184; Match(SEMICOLON);
				}
				break;
			case CURLYBL:
				EnterOuterAlt(_localctx, 10);
				{
				State = 186; block();
				}
				break;
			case SEMICOLON:
				EnterOuterAlt(_localctx, 11);
				{
				State = 187; Match(SEMICOLON);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode CURLYBL() { return GetToken(VoltaParser.CURLYBL, 0); }
		public ITerminalNode CURLYBR() { return GetToken(VoltaParser.CURLYBR, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ConstDeclContext[] constDecl() {
			return GetRuleContexts<ConstDeclContext>();
		}
		public ConstDeclContext constDecl(int i) {
			return GetRuleContext<ConstDeclContext>(i);
		}
		public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 16, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190; Match(CURLYBL);
			State = 196;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << SEMICOLON) | (1L << CURLYBL) | (1L << CONST) | (1L << IF) | (1L << READ) | (1L << RETURN) | (1L << WHILE) | (1L << WRITE) | (1L << FOR) | (1L << SWITCH) | (1L << BREAK) | (1L << IDENT))) != 0)) {
				{
				State = 194;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
				case 1:
					{
					State = 191; statement();
					}
					break;
				case 2:
					{
					State = 192; constDecl();
					}
					break;
				case 3:
					{
					State = 193; varDecl();
					}
					break;
				}
				}
				State = 198;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 199; Match(CURLYBR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActParsContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(VoltaParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(VoltaParser.COMMA, i);
		}
		public ActParsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actPars; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterActPars(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitActPars(this);
		}
	}

	[RuleVersion(0)]
	public ActParsContext actPars() {
		ActParsContext _localctx = new ActParsContext(Context, State);
		EnterRule(_localctx, 18, RULE_actPars);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201; expr();
			State = 206;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 202; Match(COMMA);
				State = 203; expr();
				}
				}
				State = 208;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		public CondTermContext[] condTerm() {
			return GetRuleContexts<CondTermContext>();
		}
		public CondTermContext condTerm(int i) {
			return GetRuleContext<CondTermContext>(i);
		}
		public ITerminalNode[] OR() { return GetTokens(VoltaParser.OR); }
		public ITerminalNode OR(int i) {
			return GetToken(VoltaParser.OR, i);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterCondition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitCondition(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 20, RULE_condition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209; condTerm();
			State = 214;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OR) {
				{
				{
				State = 210; Match(OR);
				State = 211; condTerm();
				}
				}
				State = 216;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondTermContext : ParserRuleContext {
		public CondFactContext[] condFact() {
			return GetRuleContexts<CondFactContext>();
		}
		public CondFactContext condFact(int i) {
			return GetRuleContext<CondFactContext>(i);
		}
		public ITerminalNode[] AND() { return GetTokens(VoltaParser.AND); }
		public ITerminalNode AND(int i) {
			return GetToken(VoltaParser.AND, i);
		}
		public CondTermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condTerm; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterCondTerm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitCondTerm(this);
		}
	}

	[RuleVersion(0)]
	public CondTermContext condTerm() {
		CondTermContext _localctx = new CondTermContext(Context, State);
		EnterRule(_localctx, 22, RULE_condTerm);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 217; condFact();
			State = 222;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==AND) {
				{
				{
				State = 218; Match(AND);
				State = 219; condFact();
				}
				}
				State = 224;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondFactContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public RelopContext relop() {
			return GetRuleContext<RelopContext>(0);
		}
		public CondFactContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condFact; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterCondFact(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitCondFact(this);
		}
	}

	[RuleVersion(0)]
	public CondFactContext condFact() {
		CondFactContext _localctx = new CondFactContext(Context, State);
		EnterRule(_localctx, 24, RULE_condFact);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225; expr();
			State = 226; relop();
			State = 227; expr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		public ITerminalNode SUB() { return GetToken(VoltaParser.SUB, 0); }
		public AddopContext[] addop() {
			return GetRuleContexts<AddopContext>();
		}
		public AddopContext addop(int i) {
			return GetRuleContext<AddopContext>(i);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 26, RULE_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SUB) {
				{
				State = 229; Match(SUB);
				}
			}

			State = 232; term();
			State = 238;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ADD || _la==SUB) {
				{
				{
				State = 233; addop();
				State = 234; term();
				}
				}
				State = 240;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public FactorContext[] factor() {
			return GetRuleContexts<FactorContext>();
		}
		public FactorContext factor(int i) {
			return GetRuleContext<FactorContext>(i);
		}
		public MulopContext[] mulop() {
			return GetRuleContexts<MulopContext>();
		}
		public MulopContext mulop(int i) {
			return GetRuleContext<MulopContext>(i);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 28, RULE_term);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 241; factor();
			State = 247;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MUL) | (1L << DIV) | (1L << MDIV))) != 0)) {
				{
				{
				State = 242; mulop();
				State = 243; factor();
				}
				}
				State = 249;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		public DesignatorContext designator() {
			return GetRuleContext<DesignatorContext>(0);
		}
		public ITerminalNode BL() { return GetToken(VoltaParser.BL, 0); }
		public ITerminalNode BR() { return GetToken(VoltaParser.BR, 0); }
		public ActParsContext actPars() {
			return GetRuleContext<ActParsContext>(0);
		}
		public ITerminalNode NUM() { return GetToken(VoltaParser.NUM, 0); }
		public ITerminalNode CHARCONST() { return GetToken(VoltaParser.CHARCONST, 0); }
		public ITerminalNode TRUE() { return GetToken(VoltaParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(VoltaParser.FALSE, 0); }
		public ITerminalNode NEW() { return GetToken(VoltaParser.NEW, 0); }
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterFactor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitFactor(this);
		}
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(Context, State);
		EnterRule(_localctx, 30, RULE_factor);
		int _la;
		try {
			State = 267;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 250; designator();
				State = 256;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==BL) {
					{
					State = 251; Match(BL);
					State = 253;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << BL) | (1L << SUB) | (1L << NEW) | (1L << TRUE) | (1L << FALSE) | (1L << IDENT) | (1L << NUM) | (1L << CHARCONST))) != 0)) {
						{
						State = 252; actPars();
						}
					}

					State = 255; Match(BR);
					}
				}

				}
				break;
			case NUM:
				EnterOuterAlt(_localctx, 2);
				{
				State = 258; Match(NUM);
				}
				break;
			case CHARCONST:
				EnterOuterAlt(_localctx, 3);
				{
				State = 259; Match(CHARCONST);
				}
				break;
			case TRUE:
			case FALSE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 260;
				_la = TokenStream.LA(1);
				if ( !(_la==TRUE || _la==FALSE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case NEW:
				EnterOuterAlt(_localctx, 5);
				{
				State = 261; Match(NEW);
				State = 262; Match(IDENT);
				}
				break;
			case BL:
				EnterOuterAlt(_localctx, 6);
				{
				State = 263; Match(BL);
				State = 264; expr();
				State = 265; Match(BR);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DesignatorContext : ParserRuleContext {
		public ITerminalNode[] IDENT() { return GetTokens(VoltaParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(VoltaParser.IDENT, i);
		}
		public ITerminalNode[] DOT() { return GetTokens(VoltaParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(VoltaParser.DOT, i);
		}
		public ITerminalNode[] SQUAREBL() { return GetTokens(VoltaParser.SQUAREBL); }
		public ITerminalNode SQUAREBL(int i) {
			return GetToken(VoltaParser.SQUAREBL, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] SQUAREBR() { return GetTokens(VoltaParser.SQUAREBR); }
		public ITerminalNode SQUAREBR(int i) {
			return GetToken(VoltaParser.SQUAREBR, i);
		}
		public DesignatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_designator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterDesignator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitDesignator(this);
		}
	}

	[RuleVersion(0)]
	public DesignatorContext designator() {
		DesignatorContext _localctx = new DesignatorContext(Context, State);
		EnterRule(_localctx, 32, RULE_designator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 269; Match(IDENT);
			State = 278;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SQUAREBL || _la==DOT) {
				{
				State = 276;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case DOT:
					{
					State = 270; Match(DOT);
					State = 271; Match(IDENT);
					}
					break;
				case SQUAREBL:
					{
					State = 272; Match(SQUAREBL);
					State = 273; expr();
					State = 274; Match(SQUAREBR);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 280;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulopContext : ParserRuleContext {
		public ITerminalNode MUL() { return GetToken(VoltaParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(VoltaParser.DIV, 0); }
		public ITerminalNode MDIV() { return GetToken(VoltaParser.MDIV, 0); }
		public MulopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterMulop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitMulop(this);
		}
	}

	[RuleVersion(0)]
	public MulopContext mulop() {
		MulopContext _localctx = new MulopContext(Context, State);
		EnterRule(_localctx, 34, RULE_mulop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 281;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MUL) | (1L << DIV) | (1L << MDIV))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddopContext : ParserRuleContext {
		public ITerminalNode ADD() { return GetToken(VoltaParser.ADD, 0); }
		public ITerminalNode SUB() { return GetToken(VoltaParser.SUB, 0); }
		public AddopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterAddop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitAddop(this);
		}
	}

	[RuleVersion(0)]
	public AddopContext addop() {
		AddopContext _localctx = new AddopContext(Context, State);
		EnterRule(_localctx, 36, RULE_addop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			_la = TokenStream.LA(1);
			if ( !(_la==ADD || _la==SUB) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelopContext : ParserRuleContext {
		public ITerminalNode EQUALEQUAL() { return GetToken(VoltaParser.EQUALEQUAL, 0); }
		public ITerminalNode NOTEQUAL() { return GetToken(VoltaParser.NOTEQUAL, 0); }
		public ITerminalNode GREATEREQUAL() { return GetToken(VoltaParser.GREATEREQUAL, 0); }
		public ITerminalNode LESSEQUAL() { return GetToken(VoltaParser.LESSEQUAL, 0); }
		public ITerminalNode GREATER() { return GetToken(VoltaParser.GREATER, 0); }
		public ITerminalNode LESS() { return GetToken(VoltaParser.LESS, 0); }
		public RelopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterRelop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitRelop(this);
		}
	}

	[RuleVersion(0)]
	public RelopContext relop() {
		RelopContext _localctx = new RelopContext(Context, State);
		EnterRule(_localctx, 38, RULE_relop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 285;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << EQUALEQUAL) | (1L << NOTEQUAL) | (1L << GREATEREQUAL) | (1L << LESSEQUAL) | (1L << GREATER) | (1L << LESS))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwitchContext : ParserRuleContext {
		public ITerminalNode SWITCH() { return GetToken(VoltaParser.SWITCH, 0); }
		public ITerminalNode BL() { return GetToken(VoltaParser.BL, 0); }
		public ITerminalNode BR() { return GetToken(VoltaParser.BR, 0); }
		public ITerminalNode CURLYBL() { return GetToken(VoltaParser.CURLYBL, 0); }
		public ITerminalNode CURLYBR() { return GetToken(VoltaParser.CURLYBR, 0); }
		public ITerminalNode IDENT() { return GetToken(VoltaParser.IDENT, 0); }
		public ITerminalNode[] NUM() { return GetTokens(VoltaParser.NUM); }
		public ITerminalNode NUM(int i) {
			return GetToken(VoltaParser.NUM, i);
		}
		public ITerminalNode[] CHARCONST() { return GetTokens(VoltaParser.CHARCONST); }
		public ITerminalNode CHARCONST(int i) {
			return GetToken(VoltaParser.CHARCONST, i);
		}
		public ITerminalNode[] STRING() { return GetTokens(VoltaParser.STRING); }
		public ITerminalNode STRING(int i) {
			return GetToken(VoltaParser.STRING, i);
		}
		public ITerminalNode[] CASE() { return GetTokens(VoltaParser.CASE); }
		public ITerminalNode CASE(int i) {
			return GetToken(VoltaParser.CASE, i);
		}
		public ITerminalNode[] COLON() { return GetTokens(VoltaParser.COLON); }
		public ITerminalNode COLON(int i) {
			return GetToken(VoltaParser.COLON, i);
		}
		public ITerminalNode DEFAULT() { return GetToken(VoltaParser.DEFAULT, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode[] BREAK() { return GetTokens(VoltaParser.BREAK); }
		public ITerminalNode BREAK(int i) {
			return GetToken(VoltaParser.BREAK, i);
		}
		public ITerminalNode[] SEMICOLON() { return GetTokens(VoltaParser.SEMICOLON); }
		public ITerminalNode SEMICOLON(int i) {
			return GetToken(VoltaParser.SEMICOLON, i);
		}
		public SwitchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_switch; } }
		public override void EnterRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.EnterSwitch(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IVoltaParserListener typedListener = listener as IVoltaParserListener;
			if (typedListener != null) typedListener.ExitSwitch(this);
		}
	}

	[RuleVersion(0)]
	public SwitchContext @switch() {
		SwitchContext _localctx = new SwitchContext(Context, State);
		EnterRule(_localctx, 40, RULE_switch);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 287; Match(SWITCH);
			State = 288; Match(BL);
			State = 289;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IDENT) | (1L << NUM) | (1L << CHARCONST) | (1L << STRING))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 290; Match(BR);
			State = 291; Match(CURLYBL);
			State = 304;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CASE) {
				{
				{
				State = 292; Match(CASE);
				State = 293;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NUM) | (1L << CHARCONST) | (1L << STRING))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 294; Match(COLON);
				State = 300;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << SEMICOLON) | (1L << CURLYBL) | (1L << IF) | (1L << READ) | (1L << RETURN) | (1L << WHILE) | (1L << WRITE) | (1L << FOR) | (1L << SWITCH) | (1L << BREAK) | (1L << IDENT))) != 0)) {
					{
					State = 295; statement();
					State = 298;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==BREAK) {
						{
						State = 296; Match(BREAK);
						State = 297; Match(SEMICOLON);
						}
					}

					}
				}

				}
				}
				State = 306;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 316;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DEFAULT) {
				{
				State = 307; Match(DEFAULT);
				State = 308; Match(COLON);
				State = 314;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << SEMICOLON) | (1L << CURLYBL) | (1L << IF) | (1L << READ) | (1L << RETURN) | (1L << WHILE) | (1L << WRITE) | (1L << FOR) | (1L << SWITCH) | (1L << BREAK) | (1L << IDENT))) != 0)) {
					{
					State = 309; statement();
					State = 312;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==BREAK) {
						{
						State = 310; Match(BREAK);
						State = 311; Match(SEMICOLON);
						}
					}

					}
				}

				}
			}

			State = 318; Match(CURLYBR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x37', '\x143', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\a', '\x2', '\x32', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', '\x35', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x39', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', '<', '\v', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 'L', '\n', '\x4', 
		'\f', '\x4', '\xE', '\x4', 'O', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '[', '\n', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '`', '\n', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\a', '\x6', '\x64', '\n', '\x6', '\f', '\x6', 
		'\xE', '\x6', 'g', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', 
		'\a', 'q', '\n', '\a', '\f', '\a', '\xE', '\a', 't', '\v', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 'y', '\n', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x80', 
		'\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x85', 
		'\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 
		'\x90', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x5', '\t', '\x97', '\n', '\t', '\x3', '\t', '\x3', '\t', 
		'\x5', '\t', '\x9B', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x5', '\t', '\xAB', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\xB8', '\n', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 
		'\xBF', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\a', '\n', '\xC5', '\n', '\n', '\f', '\n', '\xE', '\n', '\xC8', '\v', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\a', '\v', '\xCF', '\n', '\v', '\f', '\v', '\xE', '\v', '\xD2', '\v', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\xD7', '\n', 
		'\f', '\f', '\f', '\xE', '\f', '\xDA', '\v', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\a', '\r', '\xDF', '\n', '\r', '\f', '\r', '\xE', 
		'\r', '\xE2', '\v', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x5', '\xF', '\xE9', '\n', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\a', '\xF', '\xEF', '\n', '\xF', 
		'\f', '\xF', '\xE', '\xF', '\xF2', '\v', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\xF8', '\n', '\x10', 
		'\f', '\x10', '\xE', '\x10', '\xFB', '\v', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x5', '\x11', '\x100', '\n', '\x11', '\x3', '\x11', 
		'\x5', '\x11', '\x103', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x5', '\x11', '\x10E', '\n', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\a', '\x12', '\x117', '\n', '\x12', '\f', '\x12', '\xE', 
		'\x12', '\x11A', '\v', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', 
		'\x12D', '\n', '\x16', '\x5', '\x16', '\x12F', '\n', '\x16', '\a', '\x16', 
		'\x131', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\x134', '\v', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x5', '\x16', '\x13B', '\n', '\x16', '\x5', '\x16', '\x13D', '\n', '\x16', 
		'\x5', '\x16', '\x13F', '\n', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x2', '\x2', '\x17', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', 
		'\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', 
		'$', '&', '(', '*', '\x2', '\b', '\x3', '\x2', '\x33', '\x35', '\x3', 
		'\x2', '+', ',', '\x3', '\x2', '\xF', '\x11', '\x4', '\x2', '\v', '\v', 
		'\r', '\r', '\x4', '\x2', '\x12', '\x15', '\x17', '\x18', '\x3', '\x2', 
		'\x32', '\x35', '\x2', '\x162', '\x2', ',', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '@', '\x3', '\x2', '\x2', '\x2', '\x6', 'G', '\x3', '\x2', '\x2', 
		'\x2', '\b', 'R', '\x3', '\x2', '\x2', '\x2', '\n', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\f', 'j', '\x3', '\x2', '\x2', '\x2', '\xE', 'u', '\x3', 
		'\x2', '\x2', '\x2', '\x10', '\xBE', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\x14', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\xD3', '\x3', '\x2', '\x2', '\x2', '\x18', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\xE3', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xF3', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\x10D', '\x3', '\x2', '\x2', '\x2', '\"', '\x10F', '\x3', 
		'\x2', '\x2', '\x2', '$', '\x11B', '\x3', '\x2', '\x2', '\x2', '&', '\x11D', 
		'\x3', '\x2', '\x2', '\x2', '(', '\x11F', '\x3', '\x2', '\x2', '\x2', 
		'*', '\x121', '\x3', '\x2', '\x2', '\x2', ',', '-', '\a', '!', '\x2', 
		'\x2', '-', '\x33', '\a', '\x32', '\x2', '\x2', '.', '\x32', '\x5', '\x4', 
		'\x3', '\x2', '/', '\x32', '\x5', '\x6', '\x4', '\x2', '\x30', '\x32', 
		'\x5', '\b', '\x5', '\x2', '\x31', '.', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x31', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x35', '\x3', '\x2', '\x2', '\x2', '\x33', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x36', ':', '\a', '\x19', '\x2', '\x2', '\x37', '\x39', '\x5', 
		'\n', '\x6', '\x2', '\x38', '\x37', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'<', '\x3', '\x2', '\x2', '\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', 
		':', ';', '\x3', '\x2', '\x2', '\x2', ';', '=', '\x3', '\x2', '\x2', '\x2', 
		'<', ':', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '\x1A', '\x2', '\x2', 
		'>', '?', '\a', '\x2', '\x2', '\x3', '?', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '@', '\x41', '\a', '\"', '\x2', '\x2', '\x41', '\x42', '\x5', '\xE', 
		'\b', '\x2', '\x42', '\x43', '\a', '\x32', '\x2', '\x2', '\x43', '\x44', 
		'\a', '\x16', '\x2', '\x2', '\x44', '\x45', '\t', '\x2', '\x2', '\x2', 
		'\x45', '\x46', '\a', '\n', '\x2', '\x2', '\x46', '\x5', '\x3', '\x2', 
		'\x2', '\x2', 'G', 'H', '\x5', '\xE', '\b', '\x2', 'H', 'M', '\a', '\x32', 
		'\x2', '\x2', 'I', 'J', '\a', '\x1F', '\x2', '\x2', 'J', 'L', '\a', '\x32', 
		'\x2', '\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 'L', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'M', 'K', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'P', '\x3', '\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'Q', '\a', '\n', '\x2', '\x2', 'Q', '\a', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'S', '\a', '!', '\x2', '\x2', 'S', 'T', '\a', '\x32', 
		'\x2', '\x2', 'T', 'U', '\a', '\x19', '\x2', '\x2', 'U', 'V', '\x5', '\x6', 
		'\x4', '\x2', 'V', 'W', '\a', '\x1A', '\x2', '\x2', 'W', '\t', '\x3', 
		'\x2', '\x2', '\x2', 'X', '[', '\x5', '\xE', '\b', '\x2', 'Y', '[', '\a', 
		'(', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', '\x2', '\x2', 'Z', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', ']', 
		'\a', '\x32', '\x2', '\x2', ']', '_', '\a', '\b', '\x2', '\x2', '^', '`', 
		'\x5', '\f', '\a', '\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '_', '`', 
		'\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x65', '\a', '\t', '\x2', '\x2', '\x62', '\x64', '\x5', '\x6', '\x4', 
		'\x2', '\x63', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', 'g', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\x3', '\x2', '\x2', '\x2', '\x66', 'h', '\x3', '\x2', '\x2', 
		'\x2', 'g', '\x65', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x5', '\x12', 
		'\n', '\x2', 'i', '\v', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x5', '\xE', 
		'\b', '\x2', 'k', 'r', '\a', '\x32', '\x2', '\x2', 'l', 'm', '\a', '\x1F', 
		'\x2', '\x2', 'm', 'n', '\x5', '\xE', '\b', '\x2', 'n', 'o', '\a', '\x32', 
		'\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 'p', 'l', '\x3', '\x2', 
		'\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', '\r', '\x3', 
		'\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 'u', 'x', '\a', 
		'\x32', '\x2', '\x2', 'v', 'w', '\a', '\x1B', '\x2', '\x2', 'w', 'y', 
		'\a', '\x1C', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 
		'y', '\x3', '\x2', '\x2', '\x2', 'y', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'z', '\x84', '\x5', '\"', '\x12', '\x2', '{', '|', '\a', '\x16', '\x2', 
		'\x2', '|', '\x85', '\x5', '\x1C', '\xF', '\x2', '}', '\x7F', '\a', '\b', 
		'\x2', '\x2', '~', '\x80', '\x5', '\x14', '\v', '\x2', '\x7F', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '\x85', '\a', '\t', '\x2', 
		'\x2', '\x82', '\x85', '\a', '\f', '\x2', '\x2', '\x83', '\x85', '\a', 
		'\xE', '\x2', '\x2', '\x84', '{', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'}', '\x3', '\x2', '\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', '\n', '\x2', '\x2', '\x87', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '$', '\x2', 
		'\x2', '\x89', '\x8A', '\a', '\b', '\x2', '\x2', '\x8A', '\x8B', '\x5', 
		'\x16', '\f', '\x2', '\x8B', '\x8C', '\a', '\t', '\x2', '\x2', '\x8C', 
		'\x8F', '\x5', '\x10', '\t', '\x2', '\x8D', '\x8E', '\a', '#', '\x2', 
		'\x2', '\x8E', '\x90', '\x5', '\x10', '\t', '\x2', '\x8F', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', '-', '\x2', 
		'\x2', '\x92', '\x93', '\a', '\b', '\x2', '\x2', '\x93', '\x94', '\x5', 
		'\x1C', '\xF', '\x2', '\x94', '\x96', '\a', '\n', '\x2', '\x2', '\x95', 
		'\x97', '\x5', '\x16', '\f', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\x9A', '\a', '\n', '\x2', '\x2', '\x99', 
		'\x9B', '\x5', '\x10', '\t', '\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9D', '\a', '\t', '\x2', '\x2', '\x9D', 
		'\x9E', '\x5', '\x10', '\t', '\x2', '\x9E', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA0', '\a', ')', '\x2', '\x2', '\xA0', '\xA1', '\a', 
		'\b', '\x2', '\x2', '\xA1', '\xA2', '\x5', '\x16', '\f', '\x2', '\xA2', 
		'\xA3', '\a', '\t', '\x2', '\x2', '\xA3', '\xA4', '\x5', '\x10', '\t', 
		'\x2', '\xA4', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', 
		'\x30', '\x2', '\x2', '\xA6', '\xBF', '\a', '\n', '\x2', '\x2', '\xA7', 
		'\xBF', '\x5', '*', '\x16', '\x2', '\xA8', '\xAA', '\a', '\'', '\x2', 
		'\x2', '\xA9', '\xAB', '\x5', '\x1C', '\xF', '\x2', '\xAA', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', '&', '\x2', 
		'\x2', '\xAD', '\xAE', '\a', '\b', '\x2', '\x2', '\xAE', '\xAF', '\x5', 
		'\"', '\x12', '\x2', '\xAF', '\xB0', '\a', '\t', '\x2', '\x2', '\xB0', 
		'\xB1', '\a', '\n', '\x2', '\x2', '\xB1', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\a', '*', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		'\b', '\x2', '\x2', '\xB4', '\xB7', '\x5', '\x1C', '\xF', '\x2', '\xB5', 
		'\xB6', '\a', '\x1F', '\x2', '\x2', '\xB6', '\xB8', '\a', '\x33', '\x2', 
		'\x2', '\xB7', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', '\t', '\x2', '\x2', '\xBA', '\xBB', '\a', '\n', '\x2', '\x2', 
		'\xBB', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBF', '\x5', '\x12', 
		'\n', '\x2', '\xBD', '\xBF', '\a', '\n', '\x2', '\x2', '\xBE', 'z', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\x88', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\xBE', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xB2', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\x11', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC6', '\a', '\x19', '\x2', '\x2', '\xC1', '\xC5', '\x5', '\x10', '\t', 
		'\x2', '\xC2', '\xC5', '\x5', '\x4', '\x3', '\x2', '\xC3', '\xC5', '\x5', 
		'\x6', '\x4', '\x2', '\xC4', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC9', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\a', '\x1A', '\x2', '\x2', '\xCA', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xD0', '\x5', '\x1C', '\xF', '\x2', '\xCC', 
		'\xCD', '\a', '\x1F', '\x2', '\x2', '\xCD', '\xCF', '\x5', '\x1C', '\xF', 
		'\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD2', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD0', 
		'\xD1', '\x3', '\x2', '\x2', '\x2', '\xD1', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD8', '\x5', 
		'\x18', '\r', '\x2', '\xD4', '\xD5', '\a', '\a', '\x2', '\x2', '\xD5', 
		'\xD7', '\x5', '\x18', '\r', '\x2', '\xD6', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD6', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDB', '\xE0', '\x5', '\x1A', '\xE', '\x2', '\xDC', '\xDD', '\a', 
		'\x6', '\x2', '\x2', '\xDD', '\xDF', '\x5', '\x1A', '\xE', '\x2', '\xDE', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\x19', '\x3', '\x2', '\x2', '\x2', '\xE2', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\x5', '\x1C', '\xF', 
		'\x2', '\xE4', '\xE5', '\x5', '(', '\x15', '\x2', '\xE5', '\xE6', '\x5', 
		'\x1C', '\xF', '\x2', '\xE6', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xE7', 
		'\xE9', '\a', '\r', '\x2', '\x2', '\xE8', '\xE7', '\x3', '\x2', '\x2', 
		'\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xF0', '\x5', '\x1E', '\x10', '\x2', '\xEB', 
		'\xEC', '\x5', '&', '\x14', '\x2', '\xEC', '\xED', '\x5', '\x1E', '\x10', 
		'\x2', '\xED', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEB', '\x3', 
		'\x2', '\x2', '\x2', '\xEF', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF1', '\x3', '\x2', '\x2', 
		'\x2', '\xF1', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF0', '\x3', 
		'\x2', '\x2', '\x2', '\xF3', '\xF9', '\x5', ' ', '\x11', '\x2', '\xF4', 
		'\xF5', '\x5', '$', '\x13', '\x2', '\xF5', '\xF6', '\x5', ' ', '\x11', 
		'\x2', '\xF6', '\xF8', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF4', '\x3', 
		'\x2', '\x2', '\x2', '\xF8', '\xFB', '\x3', '\x2', '\x2', '\x2', '\xF9', 
		'\xF7', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xFA', '\x3', '\x2', '\x2', 
		'\x2', '\xFA', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xF9', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\x102', '\x5', '\"', '\x12', '\x2', '\xFD', 
		'\xFF', '\a', '\b', '\x2', '\x2', '\xFE', '\x100', '\x5', '\x14', '\v', 
		'\x2', '\xFF', '\xFE', '\x3', '\x2', '\x2', '\x2', '\xFF', '\x100', '\x3', 
		'\x2', '\x2', '\x2', '\x100', '\x101', '\x3', '\x2', '\x2', '\x2', '\x101', 
		'\x103', '\a', '\t', '\x2', '\x2', '\x102', '\xFD', '\x3', '\x2', '\x2', 
		'\x2', '\x102', '\x103', '\x3', '\x2', '\x2', '\x2', '\x103', '\x10E', 
		'\x3', '\x2', '\x2', '\x2', '\x104', '\x10E', '\a', '\x33', '\x2', '\x2', 
		'\x105', '\x10E', '\a', '\x34', '\x2', '\x2', '\x106', '\x10E', '\t', 
		'\x3', '\x2', '\x2', '\x107', '\x108', '\a', '%', '\x2', '\x2', '\x108', 
		'\x10E', '\a', '\x32', '\x2', '\x2', '\x109', '\x10A', '\a', '\b', '\x2', 
		'\x2', '\x10A', '\x10B', '\x5', '\x1C', '\xF', '\x2', '\x10B', '\x10C', 
		'\a', '\t', '\x2', '\x2', '\x10C', '\x10E', '\x3', '\x2', '\x2', '\x2', 
		'\x10D', '\xFC', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x104', '\x3', 
		'\x2', '\x2', '\x2', '\x10D', '\x105', '\x3', '\x2', '\x2', '\x2', '\x10D', 
		'\x106', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x107', '\x3', '\x2', '\x2', 
		'\x2', '\x10D', '\x109', '\x3', '\x2', '\x2', '\x2', '\x10E', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x10F', '\x118', '\a', '\x32', '\x2', '\x2', '\x110', 
		'\x111', '\a', '\x1E', '\x2', '\x2', '\x111', '\x117', '\a', '\x32', '\x2', 
		'\x2', '\x112', '\x113', '\a', '\x1B', '\x2', '\x2', '\x113', '\x114', 
		'\x5', '\x1C', '\xF', '\x2', '\x114', '\x115', '\a', '\x1C', '\x2', '\x2', 
		'\x115', '\x117', '\x3', '\x2', '\x2', '\x2', '\x116', '\x110', '\x3', 
		'\x2', '\x2', '\x2', '\x116', '\x112', '\x3', '\x2', '\x2', '\x2', '\x117', 
		'\x11A', '\x3', '\x2', '\x2', '\x2', '\x118', '\x116', '\x3', '\x2', '\x2', 
		'\x2', '\x118', '\x119', '\x3', '\x2', '\x2', '\x2', '\x119', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x11A', '\x118', '\x3', '\x2', '\x2', '\x2', '\x11B', 
		'\x11C', '\t', '\x4', '\x2', '\x2', '\x11C', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x11D', '\x11E', '\t', '\x5', '\x2', '\x2', '\x11E', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x11F', '\x120', '\t', '\x6', '\x2', '\x2', '\x120', 
		')', '\x3', '\x2', '\x2', '\x2', '\x121', '\x122', '\a', '.', '\x2', '\x2', 
		'\x122', '\x123', '\a', '\b', '\x2', '\x2', '\x123', '\x124', '\t', '\a', 
		'\x2', '\x2', '\x124', '\x125', '\a', '\t', '\x2', '\x2', '\x125', '\x132', 
		'\a', '\x19', '\x2', '\x2', '\x126', '\x127', '\a', '/', '\x2', '\x2', 
		'\x127', '\x128', '\t', '\x2', '\x2', '\x2', '\x128', '\x12E', '\a', '\x1D', 
		'\x2', '\x2', '\x129', '\x12C', '\x5', '\x10', '\t', '\x2', '\x12A', '\x12B', 
		'\a', '\x30', '\x2', '\x2', '\x12B', '\x12D', '\a', '\n', '\x2', '\x2', 
		'\x12C', '\x12A', '\x3', '\x2', '\x2', '\x2', '\x12C', '\x12D', '\x3', 
		'\x2', '\x2', '\x2', '\x12D', '\x12F', '\x3', '\x2', '\x2', '\x2', '\x12E', 
		'\x129', '\x3', '\x2', '\x2', '\x2', '\x12E', '\x12F', '\x3', '\x2', '\x2', 
		'\x2', '\x12F', '\x131', '\x3', '\x2', '\x2', '\x2', '\x130', '\x126', 
		'\x3', '\x2', '\x2', '\x2', '\x131', '\x134', '\x3', '\x2', '\x2', '\x2', 
		'\x132', '\x130', '\x3', '\x2', '\x2', '\x2', '\x132', '\x133', '\x3', 
		'\x2', '\x2', '\x2', '\x133', '\x13E', '\x3', '\x2', '\x2', '\x2', '\x134', 
		'\x132', '\x3', '\x2', '\x2', '\x2', '\x135', '\x136', '\a', '\x31', '\x2', 
		'\x2', '\x136', '\x13C', '\a', '\x1D', '\x2', '\x2', '\x137', '\x13A', 
		'\x5', '\x10', '\t', '\x2', '\x138', '\x139', '\a', '\x30', '\x2', '\x2', 
		'\x139', '\x13B', '\a', '\n', '\x2', '\x2', '\x13A', '\x138', '\x3', '\x2', 
		'\x2', '\x2', '\x13A', '\x13B', '\x3', '\x2', '\x2', '\x2', '\x13B', '\x13D', 
		'\x3', '\x2', '\x2', '\x2', '\x13C', '\x137', '\x3', '\x2', '\x2', '\x2', 
		'\x13C', '\x13D', '\x3', '\x2', '\x2', '\x2', '\x13D', '\x13F', '\x3', 
		'\x2', '\x2', '\x2', '\x13E', '\x135', '\x3', '\x2', '\x2', '\x2', '\x13E', 
		'\x13F', '\x3', '\x2', '\x2', '\x2', '\x13F', '\x140', '\x3', '\x2', '\x2', 
		'\x2', '\x140', '\x141', '\a', '\x1A', '\x2', '\x2', '\x141', '+', '\x3', 
		'\x2', '\x2', '\x2', '&', '\x31', '\x33', ':', 'M', 'Z', '_', '\x65', 
		'r', 'x', '\x7F', '\x84', '\x8F', '\x96', '\x9A', '\xAA', '\xB7', '\xBE', 
		'\xC4', '\xC6', '\xD0', '\xD8', '\xE0', '\xE8', '\xF0', '\xF9', '\xFF', 
		'\x102', '\x10D', '\x116', '\x118', '\x12C', '\x12E', '\x132', '\x13A', 
		'\x13C', '\x13E',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
